WebApplication5/Areas/TravelGroupManagement/Controllers/CarRentalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Areas.TravelGroupManagement.Models;
using WebApplication5.Data;
using WebApplication5.Services;

namespace WebApplication5.Areas.TravelGroupManagement.Controllers
{
    [Area("TravelGroupManagement")]
    [Route("[area]/[controller]/[action]")]
    public class CarRentalController : Controller
    {
        private readonly AppDbContext _db;
        private readonly ILogger<CarRentalController> _logger;
        private readonly ISessionService _sessionService;

        public CarRentalController(AppDbContext db, ILogger<CarRentalController> logger, ISessionService sessionService)
        {
            _db = db;
            _logger = logger;
            _sessionService = sessionService;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Calling car rental index action");
            try
            {
                var cars = await _db.Cars.ToListAsync();

                var value = _sessionService.GetSessionData<int?>("Visited") ?? 0;
                _sessionService.SetSessionData("Visited", value + 1);

                ViewBag.mysession = value + 1;

                _logger.LogInformation("Hello");
                return View(cars);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(null);
            }
        }

        [HttpGet("Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            _logger.LogInformation("Calling car rental index action");
            var car = await _db.Cars.FirstOrDefaultAsync(c => c.CarRentalId == id);
            if (car == null)
            {
                return NotFound();
            }
            string modelForImagePath = car.Model.ToUpper();
            car.ImagePath = $"/images/{modelForImagePath}.jpg";
            return View(car);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarRental car)
        {
            if (ModelState.IsValid)
            {
                await _db.Cars.AddAsync(car);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        [HttpGet("Edit/{id:int}")]
        public async Task<IActionResult> Edit(int id)
        {
            var car = await _db.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpPost("Edit/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarRentalId", "Model", "Location", "RentalDateMin", "RentalDateMax", "PricePerDay", "ImagePath")] CarRental car)
        {
            if (id != car.CarRentalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(car);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await CarExists(car.CarRentalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        private async Task<bool> CarExists(int id)
        {
            return await _db.Cars.AnyAsync(e => e.CarRentalId == id);
        }

        [HttpGet("Delete/{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var car = await _db.Cars.FirstOrDefaultAsync(c => c.CarRentalId == id);
            if (car == null)
            {
                return NotFound();
            }
            string modelForImagePath = car.Model.ToUpper();
            car.ImagePath = $"/images/{modelForImagePath}.jpg";
            return View(car);
        }

        [HttpPost("DeleteConfirmed/{id:int}")]
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CarRentalId)
        {
            var car = _db.Cars.Find(CarRentalId);
            if (car != null)
            {
                _db.Cars.Remove(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        [HttpGet("Search/{searchString?}")]
        public async Task<IActionResult> Search(string searchString)
        {
            var carsQuery = from c in _db.Cars
                            select c;

            bool searchPerformed = !string.IsNullOrEmpty(searchString);

            if (searchPerformed)
            {
                carsQuery = carsQuery.Where(c => c.Model.Contains(searchString) || c.Location.Contains(searchString));
            }

            var cars = await carsQuery.ToListAsync();
            ViewData["SearchPerformed"] = searchPerformed;
            ViewData["SearchString"] = searchString;
            return View("Index", cars);
        }

    }
}

WebApplication5/Areas/TravelGroupManagement/Controllers/FlightController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using WebApplication5.Areas.TravelGroupManagement.Models;
using WebApplication5.Data;
using WebApplication5.Services;

namespace WebApplication5.Areas.TravelGroupManagement.Controllers
{
    [Area("TravelGroupManagement")]
    [Route("[area]/[controller]/[action]")]
    public class FlightController : Controller
    {
        private readonly AppDbContext _db;
        private readonly ILogger<FlightController> _logger;
        private readonly ISessionService _sessionService;

        public FlightController(AppDbContext db, ILogger<FlightController> logger, ISessionService sessionService)
        {
            _db = db;
            _logger = logger;
            _sessionService = sessionService;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Calling flight index action");
            try
            {
                var flights = await _db.Flights.ToListAsync(); 

                var value = _sessionService.GetSessionData<int?>("Visited") ?? 0;
                _sessionService.SetSessionData("Visited", value + 1);

                ViewBag.mysession = value + 1;

                _logger.LogInformation("Hello");
                return View(flights);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(null);
            }
        }

        [HttpGet("Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            _logger.LogInformation("Calling flight detail action");
            var flight = await _db.Flights.FirstOrDefaultAsync(f => f.FlightId == id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Flight flight)
        {
            if (ModelState.IsValid)
            {
                await _db.Flights.AddAsync(flight);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(flight);
        }

        [HttpGet("Edit/{id:int}")]
        public async Task<IActionResult> Edit(int id)
        {
            var flight = await _db.Flights.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        [HttpPost("Edit/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlightId, DepartureLocation, DestinationLocation, DepartureDate, ArrivalDate, NumberOfPassengers, Price")] Flight flight)
        {
            if (id != flight.FlightId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(flight);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await FlightExists(flight.FlightId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        private async Task<bool> FlightExists(int id)
        {
            return await _db.Flights.AnyAsync(e => e.FlightId == id);
        }

        [HttpGet("Delete/{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var flight = await _db.Flights.FirstOrDefaultAsync(f => f.FlightId == id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        [HttpPost("DeleteConfirmed/{id:int}")]
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int FlightId)
        {
            var flight = _db.Flights.Find(FlightId);
            if (flight != null)
            {
                _db.Flights.Remove(flight);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        [HttpGet("Search/{searchString?}")]
        public async Task<IActionResult> Search(string searchString)
        {
            var flightsQuery = from f in _db.Flights
                               select f;

            bool searchPerformed = !string.IsNullOrEmpty(searchString);

            if (searchPerformed)
            {
                flightsQuery = flightsQuery.Where(f => f.DepartureLocation.Contains(searchString) || f.DestinationLocation.Contains(searchString));
            }

            var flights = await flightsQuery.ToListAsync();
            ViewData["SearchPerformed"] = searchPerformed;
            ViewData["SearchString"] = searchString;
            return View("Index", flights);
        }

    }
}

WebApplication5/Areas/TravelGroupManagement/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Areas.TravelGroupManagement.Models;
using WebApplication5.Data;
using WebApplication5.Services;

namespace WebApplication5.Areas.TravelGroupManagement.Controllers
{
    [Area("TravelGroupManagement")]
    [Route("[area]/[controller]/[action]")]
    public class HotelController : Controller
    {

        private readonly AppDbContext _db;
        private readonly ILogger<HotelController> _logger;
        private readonly ISessionService _sessionService;

        public HotelController(AppDbContext db, ILogger<HotelController> logger, ISessionService sessionService)
        {
            _db = db;
            _logger = logger;
            _sessionService = sessionService;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Calling hotel index action");
            try
            {
                var hotels = await _db.Hotels.ToListAsync();

                var value = _sessionService.GetSessionData<int?>("Visited") ?? 0;
                _sessionService.SetSessionData("Visited", value + 1);

                ViewBag.mysession = value + 1;

                _logger.LogInformation("Hello");
                return View(hotels);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(null);
            }
        }

        [HttpGet("Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            _logger.LogInformation("Calling hotel index action");
            var hotel = await _db.Hotels.FirstOrDefaultAsync(f => f.HotelId == id);
            if (hotel == null)
            {
                return NotFound();
            }
            hotel.ImagePath = $"/images/{hotel.Name.ToUpper()}.jpg";
            return View(hotel);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                await _db.Hotels.AddAsync(hotel);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        [HttpGet("Edit/{id:int}")]
        public async Task<IActionResult> Edit(int id)
        {
            var hotel = await _db.Hotels.FindAsync(id);
            if (hotel == null)
            {
                return NotFound();
            }
            return View(hotel);
        }

        [HttpPost("Edit/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HotelId, Name, Location, CheckInDate, CheckOutDate, NumberOfGuests, Rating, PricePerNight")] Hotel hotel)
        {
            if (id != hotel.HotelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(hotel);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await HotelExists(hotel.HotelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hotel);
        }

        private async Task<bool> HotelExists(int id)
        {
            return _db.Hotels.Any(e => e.HotelId == id);
        }

        [HttpGet("Delete/{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var hotel = await _db.Hotels.FirstOrDefaultAsync(h => h.HotelId == id);
            if (hotel == null)
            {
                return NotFound();
            }
            hotel.ImagePath = $"/images/{hotel.Name.ToUpper()}.jpg";
            return View(hotel);
        }

        [HttpPost("DeleteConfirmed/{id:int}")]
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int HotelId)
        {
            var hotel = _db.Hotels.Find(HotelId);
            if (hotel != null)
            {
                _db.Hotels.Remove(hotel);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        [HttpGet("Search/{searchString?}")]
        public async Task<IActionResult> Search(string searchString)
        {
            var hotelsQuery = from h in _db.Hotels
                              select h;

            bool searchPerformed = !string.IsNullOrEmpty(searchString);

            if (searchPerformed)
            {
                hotelsQuery = hotelsQuery.Where(h => h.Name.Contains(searchString) || h.Location.Contains(searchString));
            }

            var hotels = await hotelsQuery.ToListAsync();
            ViewData["SearchPerformed"] = searchPerformed;
            ViewData["SearchString"] = searchString;
            return View("Index", hotels);
        }
    }
}

WebApplication5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication5.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
</head>
<body>
    <header>
        @Html.Partial("_Navbar")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Comp 2139 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication5/Views/Shared/_Navbar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Microsoft.AspNetCore.Identity;
@using WebApplication5.Areas.TravelGroupManagement.Models;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <img src="~/images/clouds.png" height="75px" width="75px" alt="Clouds Image" class="clouds-img" />
            </div>
            <div class="col-md-6">
                <img src="~/images/stars.png" height="75px" width="75px" alt="Stars Image" class="stars-img" />
            </div>
        </div>
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/images/logo.png" height="75px" width="75px" />
        </a>
        <img src="~/images/stars.png" height="75px" width="75px" alt="Stars Image" class="stars-img" />
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--This is the search form-->
        <form class="d-flex" asp-controller="Home" asp-action="GeneralSearch" method="get">
            <input class="form-control" type="text" placeholder="Search" name="searchString" />
            <select class="form-control btn btn-secondary dropdown-toggle" name="searchType">
                <option value="Flights">Flights</option>
                <option value="Hotels">Hotels</option>
                <option value="Cars">Cars</option>
            </select>
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i>Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About"><i class="fas fa-info-circle"></i>About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="TravelGroupManagement" asp-controller="Flight" asp-action="Index"><i class="fas fa-plane"></i>Flights</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="TravelGroupManagement" asp-controller="Hotel" asp-action="Index"><i class="fas fa-hotel"></i>Hotels</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="TravelGroupManagement" asp-controller="CarRental" asp-action="Index"><i class="fas fa-car"></i>Car Rental</a>
                </li>
                <!--Sign In Manager-->
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item d-flex align-items-center">
                        @if (UserManager.GetUserAsync(User).Result.ProfilePicture != null)
                        {
                            <img style="width: 40px; height: 40px; object-fit: cover; border-radius: 20px; margin-right: 2px;" 
                            src="data:image/*;base64,@(Convert.ToBase64String(UserManager.GetUserAsync(User).Result.ProfilePicture))"/>
                        }
                        <a class="nav-link text-dark" style="padding-left: 2px; margin-left: 0;" asp-area="Identity" asp-page="/Account/Manage/Index" 
                        title="Manage"><i class="fa fa-user-circle"></i> Profile</a>
                    </li>
                    <li class="nav-item">
                        <form asp-area="Identity" asp-page="/Account/Logout" method="post">
                            <button type="submit" class="nav-link btn btn-link text-dark" style="cursor:pointer">Logout</button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="/" asp-controller="/RoleManager"><i class="fade fa-sign-in-alt"></i> Role Manager</a>
                    </li>
                    <li class="nav-item">
                        <a clss="nav-link text-dark" asp-area="/" asp-controller="/UserRoles"><i class="fade fa-sin-in-alt"> User Roles</i></a>
                    </li>
                }
                else {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login"><i class="fa fa-sign-in-alt"></i> Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register"><i class="fa fa-user-plus"></i> Register</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>